(function(g){var window=this;var Z4=function(a,b,c){var d=b.wa();g.L(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.wc(c?c:"mqdefault.jpg");var f=b instanceof g.cB&&b.lengthSeconds?g.qL(b.lengthSeconds):null,k=!!e;e=k&&"RD"==(new g.UD(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.cB?b.ua:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Ej||g.bM("Watch $TITLE",{TITLE:b.title}),duration:f,url:b.wi(),is_live:l,is_list:k,
is_mix:e,background:c?"background-image: url("+c+")":""};b instanceof g.WD&&(d.playlist_length=b.getLength());a.update(d)},$4=function(a,b){g.V.call(this,{D:"div",
W:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.player=a;this.created=!1},a5=function(a){g.V.call(this,{D:"div",
W:["ytp-upnext","ytp-player-content"],N:{"aria-label":"{{aria_label}}"},K:[{D:"div",I:"ytp-cued-thumbnail-overlay-image",N:{style:"{{background}}"}},{D:"span",I:"ytp-upnext-top",K:[{D:"span",I:"ytp-upnext-header",V:"Up Next"},{D:"span",I:"ytp-upnext-title",V:"{{title}}"},{D:"span",I:"ytp-upnext-author",V:"{{author}}"}]},{D:"a",I:"ytp-upnext-autoplay-icon",N:{role:"button",href:"{{url}}","aria-label":"Play next video"},K:[{D:"svg",N:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},K:[{D:"circle",
I:"ytp-svg-autoplay-circle",N:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",I:"ytp-svg-autoplay-ring",N:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",I:"ytp-svg-fill",N:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",I:"ytp-upnext-bottom",K:[{D:"span",I:"ytp-upnext-cancel"},{D:"span",I:"ytp-upnext-paused",V:"Autoplay is paused"}]}]});
this.B=null;var b=this.o["ytp-upnext-cancel"];this.B=new g.V({D:"button",W:["ytp-upnext-cancel-button","ytp-button"],N:{tabindex:"0","aria-label":"Cancel autoplay"},V:"Cancel"});g.C(this,this.B);this.B.ga("click",this.BJ,this);this.B.ba(b);this.u=a;this.J=this.o["ytp-svg-autoplay-ring"];this.F=this.C=this.w=this.A=null;this.G=new g.J(this.qm,5E3,this);g.C(this,this.G);this.H=0;this.L(this.o["ytp-upnext-autoplay-icon"],"click",this.lL);this.gz();this.L(a,"autonavvisibility",this.gz);this.L(a,"mdxnowautoplaying",
this.DK);this.L(a,"mdxautoplaycanceled",this.EK);this.L(a,"mdxautoplayupnext",this.BB);3==this.u.getPresentingPlayerType()&&(a=(a=g.KK(g.CK(this.u)))?a.cE():null)&&this.BB(a);g.L(this.element,"ytp-upnext-mobile",this.u.P().o)},b5=function(a,b){if(!a.w){g.zo("a11y-announce","Up Next "+a.A.title);
a.H=(0,g.pq)();a.w=new g.J((0,g.x)(a.kp,a,b),25);a.kp(b);var c=b||g.S(a.u.P().experiments,"autoplay_time")||1E4;a.u.la("onAutonavCoundownStarted",c)}g.fn(a.element,"ytp-upnext-autoplay-paused")},d5=function(a){c5(a);
a.H=(0,g.pq)();a.kp();g.K(a.element,"ytp-upnext-autoplay-paused")},c5=function(a){a.w&&(a.w.dispose(),a.w=null)},e5=function(a,b){b=void 0===b?!1:b;
if(g.R(a.u.P().experiments,"autonav_notifications")&&b&&window.Notification&&document.hasFocus){var c=Notification.permission;"default"==c?Notification.requestPermission():"granted"!=c||document.hasFocus()||(c=a.A.wa(),a.qm(),a.C=new Notification("Up Next",{body:c.title,icon:c.wc()}),a.F=a.L(a.C,"click",a.cL),a.G.start())}c5(a);a.u.nextVideo(!1,b)},fqa=function(a){$4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.u=new g.V({D:"div",I:"ytp-subscribe-card",K:[{D:"img",I:"ytp-author-image",N:{src:b.Ed}},{D:"div",I:"ytp-subscribe-card-right",K:[{D:"div",I:"ytp-author-name",V:b.author},{D:"div",I:"html5-subscribe-button-container"}]}]});g.C(this,this.u);this.u.ba(this.element);this.w=new g.zP("Subscribe",null,"Unsubscribe",null,!0,!1,b.fg,b.subscribed,"trailer-endscreen",null,null,a);g.C(this,this.w);this.w.ba(this.u.o["html5-subscribe-button-container"]);this.hide()},f5=function(a){var b=
a.P(),c=g.Kv||g.lh?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.V.call(this,{D:"a",W:e,N:{href:"{{url}}",target:d?b.A:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{D:"div",I:"ytp-videowall-still-image",N:{style:"{{background}}"}},{D:"span",I:"ytp-videowall-still-info",K:[{D:"span",I:"ytp-videowall-still-info-bg",K:[{D:"span",I:"ytp-videowall-still-info-content",N:c,K:[{D:"span",I:"ytp-videowall-still-info-title",V:"{{title}}"},{D:"span",I:"ytp-videowall-still-info-author",
V:"{{author_and_views}}"},{D:"span",I:"ytp-videowall-still-info-live",V:"Live"},{D:"span",I:"ytp-videowall-still-info-duration",V:"{{duration}}"}]}]}]},{D:"span",W:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",I:"ytp-videowall-still-listlabel-length",K:[" (",{D:"span",V:"{{playlist_length}}"},")"]}]},{D:"span",W:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-mix-icon"},
"Mix",{D:"span",I:"ytp-videowall-still-listlabel-length",V:" (50+)"}]}]});this.B=d;this.u=a;this.w=null;this.A=new g.P(this);g.C(this,this.A);this.ga("click",this.F);this.ga("keypress",this.G);this.A.L(a,"videodatachange",this.C);g.dL(a,this.element,this);this.C()},gqa=function(a){var b=a.w.wa().videoId,c=a.w.getPlaylistId();
(g.IS(a.u.app,b,a.w.Ib,c,void 0,void 0)||a.u.fa("web_player_endscreen_double_log_fix_killswitch"))&&g.fL(a.u,a.element)},g5=function(a){$4.call(this,a,"videowall-endscreen");
this.F=a;this.C=0;this.w=[];this.G=this.T=this.B=null;this.H=this.U=!1;this.S=null;this.A=new g.P(this);g.C(this,this.A);this.J=new g.J(g.Ma(g.K,this.element,"ytp-show-tiles"),0);g.C(this,this.J);var b=new g.V({D:"button",W:["ytp-button","ytp-endscreen-previous"],N:{"aria-label":"Previous"},K:[g.yL()]});g.C(this,b);b.ba(this.element);b.ga("click",this.UG,this);this.O=new g.zC({D:"div",I:"ytp-endscreen-content"});g.C(this,this.O);this.O.ba(this.element);b=new g.V({D:"button",W:["ytp-button","ytp-endscreen-next"],
N:{"aria-label":"Next"},K:[g.zL()]});g.C(this,b);b.ba(this.element);b.ga("click",this.TG,this);this.u=new a5(a);g.C(this,this.u);g.aL(this.player,this.u.element,4);this.hide()},h5=function(a){return g.bL(a.player)&&a.Vu()&&!a.G},hqa=function(a,b){return(0,g.yf)(b.suggestions,function(c){c=g.bN(a.F.P(),c);
g.C(a,c);return c})},i5=function(a){var b=a.Fr();
b!=a.U&&(a.U=b,a.player.R("autonavvisibility"))},j5=function(a){g.UO.call(this,a);
this.o=null;this.u=new g.P(this);g.C(this,this.u);this.w=a.P();iqa(a)?this.o=new g5(this.player):this.w.Ma?this.o=new fqa(this.player):this.o=new $4(this.player);g.C(this,this.o);g.aL(this.player,this.o.element,4);this.zA();this.u.L(a,"videodatachange",this.zA,this);this.u.L(a,g.TD("endscreen"),this.OF,this);this.u.L(a,"crx_endscreen",this.PF,this)},iqa=function(a){a=a.P();
return a.Ka&&!a.Ma};
g.r($4,g.V);$4.prototype.create=function(){this.created=!0};
$4.prototype.destroy=function(){this.created=!1};
$4.prototype.Vu=function(){return!1};
$4.prototype.Fr=function(){return!1};g.r(a5,g.V);g.h=a5.prototype;g.h.qm=function(){this.C&&(this.G.stop(),this.Va(this.F),this.F=null,this.C.close(),this.C=null)};
g.h.gz=function(){g.DC(this,g.DK(this.u))};
g.h.cL=function(){window.focus();this.qm()};
g.h.hide=function(){g.V.prototype.hide.call(this)};
g.h.kp=function(a){a=a||g.S(this.u.P().experiments,"autoplay_time")||1E4;var b=Math.min((0,g.pq)()-this.H,a);a=Math.min(b/a,1);this.J.setAttribute("stroke-dashoffset",-211*(a+1));1<=a&&3!=this.u.getPresentingPlayerType()?e5(this,!0):this.w&&this.w.start()};
g.h.lL=function(a){!g.Ud(this.B.element,g.Gq(a))&&g.hM(a,this.u)&&e5(this)};
g.h.BJ=function(){g.FK(this.u,!0)};
g.h.DK=function(a){this.u.getPresentingPlayerType();this.show();b5(this,a)};
g.h.BB=function(a){this.u.getPresentingPlayerType();this.A&&this.A.wa().videoId==a.wa().videoId||(this.A=a,Z4(this,a,"hqdefault.jpg"))};
g.h.EK=function(){this.u.getPresentingPlayerType();c5(this);this.hide()};
g.h.X=function(){c5(this);this.qm();g.V.prototype.X.call(this)};g.r(fqa,$4);g.r(f5,g.V);f5.prototype.F=function(a){g.hM(a,this.u,this.B,this.w.Ib||void 0)&&gqa(this)};
f5.prototype.G=function(a){switch(a.keyCode){case 13:case 32:g.Lq(a)||(gqa(this),g.Kq(a))}};
f5.prototype.C=function(){var a=this.u.getVideoData(),b=this.u.P();this.B=a.kc?!1:b.u};g.r(g5,$4);g.h=g5.prototype;g.h.create=function(){$4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.B=hqa(this,a),this.T=a);this.ag();this.A.L(this.player,"appresize",this.ag);this.A.L(this.player,"onVideoAreaChange",this.ag);this.A.L(this.player,"videodatachange",this.VG);this.A.L(this.player,"autonavchange",this.Gr);this.A.L(this.player,"autonavcancel",this.SG);a=this.T.autonavState;a!=this.S&&this.Gr(a);this.A.L(this.element,"transitionend",this.zM)};
g.h.destroy=function(){g.Dr(this.A);g.de(this.w);this.w=[];this.B=null;$4.prototype.destroy.call(this);g.fn(this.element,"ytp-show-tiles");this.J.stop();this.S=this.T.autonavState};
g.h.Vu=function(){return 1!=this.T.autonavState};
g.h.show=function(){$4.prototype.show.call(this);g.fn(this.element,"ytp-show-tiles");this.player.P().o?g.Wm(this.J):this.J.start();(this.H||this.G&&this.G!=this.T.clientPlaybackNonce)&&g.FK(this.player,!1);h5(this)?(i5(this),2==this.T.autonavState?g.R(this.player.P().experiments,"fast_autonav_in_background")&&3==this.player.getVisibilityState()?e5(this.u,!0):b5(this.u):3==this.T.autonavState&&d5(this.u)):(g.FK(this.player,!0),i5(this))};
g.h.hide=function(){$4.prototype.hide.call(this);d5(this.u);i5(this)};
g.h.zM=function(a){g.Gq(a)==this.element&&this.ag()};
g.h.ag=function(){if(this.B&&this.B.length){g.K(this.element,"ytp-endscreen-paginate");var a=g.SK(this.F,!0,this.F.isFullscreen()),b=g.UC(this.F);b&&(b=b.Xb()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.B.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,t=e/2,v=b<=f-2&&n>=t*m,y=e<=k-2&&n>=q*m;if((q+1)/t*d/c>c/(q/(t+1)*d)&&y)n-=q*m,e+=2;else if(v)n-=t*m,b+=2;else if(y)n-=
q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;m*=g.jd(a.width/m||1,1,1.21);n*=g.jd(a.height/n||1,1,1.21);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.O.element;g.Bh(a,m,n);g.ih(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.u;f=this.B[0];c.A=f;Z4(c,f,"hqdefault.jpg");g.L(this.element,"ytp-endscreen-takeover",h5(this));i5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=
c,t=0,d&&f>=b-2&&k>=e-2?t=1:0==k%2&&0==f%2&&(2>k&&2>f?0==k&&0==f&&(t=2):t=2),q=g.kd(q+this.C,l),0!=t){v=this.w[c];v||(v=new f5(this.player),this.w[c]=v,a.appendChild(v.element));y=Math.floor(n*k/e);var B=Math.floor(m*f/b),D=Math.floor(n*(k+t)/e)-y-4,H=Math.floor(m*(f+t)/b)-B-4;g.qh(v.element,B,y);g.Bh(v.element,H,D);g.ih(v.element,"transitionDelay",(k+f)/20+"s");g.L(v.element,"ytp-videowall-still-mini",1==t);g.L(v.element,"ytp-videowall-still-large",2<t);t=v;q=this.B[q];t.w!=q&&(t.w=q,Z4(t,q,g.dn(t.element,
"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg"),(q=(q=q.Ib)&&q.itct)&&g.eL(t.u,t.element,q));c++}g.L(this.element,"ytp-endscreen-paginate",c<l);for(b=this.w.length-1;b>=c;b--)e=this.w[b],g.Qd(e.element),g.ce(e);this.w.length=c}};
g.h.VG=function(){var a=this.player.getVideoData();this.T!=a&&(this.C=0,this.B=hqa(this,a),this.T=a,this.ag())};
g.h.TG=function(){this.C+=this.w.length;this.ag()};
g.h.UG=function(){this.C-=this.w.length;this.ag()};
g.h.fF=function(){return!!this.u.w};
g.h.Gr=function(a){1==a?(this.H=!1,this.G=this.T.clientPlaybackNonce,c5(this.u),this.Ia()&&this.ag()):(this.H=!0,this.Ia()&&h5(this)&&(2==a?b5(this.u):3==a&&d5(this.u)))};
g.h.SG=function(a){if(a){for(a=0;a<this.w.length;a++)g.gL(this.F,this.w[a].element,!0);this.Gr(1)}else this.G=null,this.H=!1;this.ag()};
g.h.Fr=function(){return this.Ia()&&h5(this)};g.r(j5,g.UO);g.h=j5.prototype;g.h.Kx=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!iqa(this.player)||b;var c=a.di||g.Gx(a.Na),d=g.bS(this.player.app);a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.h.Jx=function(){return this.o.Fr()};
g.h.YE=function(){return this.Jx()?this.o.fF():!1};
g.h.X=function(){g.jQ(this.player.app,"endscreen",void 0);g.UO.prototype.X.call(this)};
g.h.load=function(){g.UO.prototype.load.call(this);this.o.show()};
g.h.unload=function(){g.UO.prototype.unload.call(this);this.o.hide();this.o.destroy()};
g.h.OF=function(a){this.Kx()&&(this.o.created||this.o.create(),"load"==a.getId()&&this.load())};
g.h.PF=function(a){"load"==a.getId()&&this.loaded&&this.unload()};
g.h.zA=function(){g.jQ(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.QD(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});g.C(this,a);var b=new g.QD(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.C(this,b);g.XK(this.player,[a,b])};g.iP.endscreen=j5;})(_yt_player);
